### ISSUE TITLE
Catch and log exceptions on signal handlers?

### ISSUE THREAD

**Issue by sccolbert** [phosphorjs/phosphor-signaling#7]
In the DOM world, event listeners which throw exceptions have their errors logged, but do not effect other listeners. I'm thinking that might be a good model to mimic. Most people write their code expecting signal emission to not throw, and this could help eliminate an entire class of bugs.

Thoughts?

@afshin @blink1073 @dwillmer @ellisonbg @jdfreder

**Comment by ellisonbg** [comment]
My initial take is that this makes sense.

On Wed, Nov 25, 2015 at 4:45 PM, S. Chris Colbert <notifications@github.com>
wrote:

> In the DOM world, event listeners which throw exceptions have their errors
> logged, but do not effect other listeners. I'm thinking that might be a
> good model to mimic. Most people code expected signal emission to not
> throw, and could help eliminate an entire class of bugs.
>
> Thoughts?
>
> @afshin <https://github.com/afshin> @blink1073
> <https://github.com/blink1073> @dwillmer <https://github.com/dwillmer>
> @ellisonbg <https://github.com/ellisonbg> @jdfreder
> <https://github.com/jdfreder>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phosphorjs/phosphor-signaling/issues/7>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by dwillmer** [comment]
:+1:

**Comment by afshin** [comment]
I think we should be immune from broken event listeners, whether they `throw` on purpose or by accident.

:+1:

**Comment by blink1073** [comment]
:+1:
